import { useRef, useState } from 'react'
import { Activity, CheckCircle2, Clock3, CloudUpload, FileVideo, LogOut, ShieldCheck, UploadCloud, X } from 'lucide-react'
import { useAuth } from '../auth/AuthProvider'
import { supabase, videoBucket } from '../lib/supabase'

export default function DriverDashboard() {
  const { profile, signOut } = useAuth()
  const inputRef = useRef(null)
  const [file, setFile] = useState(null)
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const onFile = (nextFile) => { setError(''); setMessage(''); if (!nextFile) return; if (!nextFile.type.startsWith('video/')) return setError('Choose a video file.'); if (nextFile.size > 500 * 1024 * 1024) return setError('Videos must be smaller than 500 MB.'); setFile(nextFile) }
  const upload = async () => { if (!file || !supabase || !profile) return; setBusy(true); setError(''); setMessage(''); const safeName = file.name.replace(/[^a-z0-9._-]/gi, '-'); const path = `${profile.id}/${Date.now()}-${safeName}`; const result = await supabase.storage.from(videoBucket).upload(path, file, { cacheControl: '3600', upsert: false, contentType: file.type }); if (result.error) setError(result.error.message); else { setMessage(`Uploaded to ${videoBucket}. The file is ready for ML processing.`); setFile(null) } setBusy(false) }
  return <div className="driver-shell"><header className="driver-topbar"><div className="driver-brand"><span className="driver-logo"><img src="/sih-logo.png" alt="SIH logo" /></span><div><strong>UrbanEye</strong><span>Driver workspace</span></div></div><div className="driver-user"><div><strong>{profile?.full_name}</strong><span>{profile?.bus_id || 'Field operator'}</span></div><button className="icon-btn" title="Sign out" onClick={signOut}><LogOut size={17} /></button></div></header><main className="driver-content"><div className="driver-hero"><div><div className="eyebrow">Mobile sensing fleet</div><h1>Capture the city.</h1><p>Upload a clear road video from <strong>{profile?.bus_id || 'your assigned bus'}</strong> and send it to the intelligence pipeline.</p></div><div className="driver-status"><i /><span>Driver channel ready</span></div></div><div className="driver-grid"><section className="driver-upload-panel"><div className="driver-section-head"><div><div className="eyebrow">Field evidence</div><h2>Upload bus footage</h2><p>Use MP4, MOV or WebM files up to 500 MB.</p></div><FileVideo size={22} /></div><button className={`dropzone ${file ? 'has-file' : ''}`} onClick={() => inputRef.current?.click()} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); onFile(event.dataTransfer.files?.[0]) }}><input ref={inputRef} type="file" accept="video/*" hidden onChange={(event) => onFile(event.target.files?.[0])} />{file ? <><span className="file-icon"><FileVideo size={25} /></span><strong>{file.name}</strong><span>{(file.size / (1024 * 1024)).toFixed(1)} MB · Ready to upload</span><span className="dropzone-change">Choose a different file</span></> : <><span className="upload-icon"><CloudUpload size={28} /></span><strong>Drop video here or browse files</strong><span>Footage stays linked to your driver account</span></>}</button>{error && <div className="driver-error"><X size={15} />{error}</div>}{message && <div className="driver-success"><CheckCircle2 size={15} />{message}</div>}<button className="driver-upload-btn" onClick={upload} disabled={!file || busy}>{busy ? 'Uploading footage…' : <><UploadCloud size={16} /> Upload for processing</>}</button></section><section className="driver-side-panel"><div className="driver-mini-card"><span><ShieldCheck size={17} /></span><div><strong>Secure handoff</strong><p>Files are stored in your private Supabase bucket and tagged to {profile?.bus_id || 'your bus'}.</p></div></div><div className="driver-mini-card"><span><Activity size={17} /></span><div><strong>What the model sees</strong><p>Road hazards, traffic conditions and safety incidents are extracted at the edge.</p></div></div><div className="driver-mini-card"><span><Clock3 size={17} /></span><div><strong>Latest handoffs</strong><p>Your recent uploads will appear here once processing history is connected.</p></div></div></section></div></main></div>
}
