import { useMemo, useState } from 'react'
import { ArrowUpRight, BusFront, Check, ExternalLink, Filter, MapPin, Search, ShieldAlert, X } from 'lucide-react'
import { apiService } from '../services/api'
import { FeedState, SectionHeading, StatusPill } from '../components/ui'
import { confidence, coord, relativeTime, shortTime, titleCase } from '../utils/format'

const statuses = ['ALL', 'NEW', 'ACKNOWLEDGED', 'INVESTIGATING', 'RESOLVED']
export default function Incidents({ incidents, loading, error, refresh }) { const [status, setStatus] = useState('ALL'); const [selected, setSelected] = useState(null); const [query, setQuery] = useState(''); const filtered = useMemo(() => incidents.filter((item) => (status === 'ALL' || item.status === status) && (!query || `${item.incident_type} ${item.bus_id} ${item.vehicle_number || ''}`.toLowerCase().includes(query.toLowerCase()))), [incidents, status, query]); return <div className="page"><div className="page-top"><div><div className="eyebrow">Safety command queue</div><h1>Incident monitoring</h1><p>Review, assign and resolve live safety signals from the bus network.</p></div><div className="page-top-badge"><ShieldAlert size={16} /> {incidents.length} total signals</div></div><section className="panel"><div className="toolbar"><div className="status-tabs">{statuses.map((item) => <button className={status === item ? 'selected' : ''} onClick={() => setStatus(item)} key={item}>{item === 'ALL' ? 'All' : titleCase(item)}</button>)}</div><div className="search-field"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search bus, type or plate" /></div><button className="icon-btn" title="Filter incidents"><Filter size={17} /></button></div><FeedState loading={loading} error={error && !incidents.length ? error : ''} empty={!filtered.length} onRetry={refresh}><div className="incident-table"><div className="table-head"><span>Signal</span><span>Location</span><span>Confidence</span><span>State</span><span>Detected</span><span /></div>{filtered.map((item) => <button className={`incident-card ${String(item.severity).toLowerCase() === 'high' ? 'high' : ''}`} key={item.id} onClick={() => setSelected(item)}><span className={`incident-marker marker-${String(item.severity || '').toLowerCase()}`}><ShieldAlert size={16} /></span><span className="incident-name"><strong>{titleCase(item.incident_type)}</strong><small><BusFront size={13} /> {item.bus_id}{item.vehicle_number ? ` · ${item.vehicle_number}` : ''}</small></span><span className="location-cell"><MapPin size={13} />{coord(item.location)}</span><span className="confidence-cell"><b>{confidence(item.confidence)}</b><i><em style={{ width: `${Number(item.confidence || 0) * 100}%` }} /></i></span><StatusPill value={item.status} /><span className="detected-cell">{relativeTime(item.timestamp)}<small>{shortTime(item.timestamp)}</small></span><ArrowUpRight size={17} className="row-arrow" /></button>)}</div></FeedState></section>{selected && <IncidentDrawer incident={selected} onClose={() => setSelected(null)} onUpdated={() => { setSelected(null); refresh() }} />}</div> }

function IncidentDrawer({ incident, onClose, onUpdated }) { const [busy, setBusy] = useState(false); const changeStatus = async (status) => { setBusy(true); try { await apiService.updateIncidentStatus(incident.id, status); onUpdated() } finally { setBusy(false) } }; return <div className="drawer-scrim" onClick={onClose}><aside className="incident-drawer" onClick={(e) => e.stopPropagation()}><div className="drawer-head"><div><div className="eyebrow">Incident investigation</div><h2>{titleCase(incident.incident_type)}</h2></div><button className="icon-btn" onClick={onClose}><X size={18} /></button></div><div className="drawer-severity"><span className={`incident-marker marker-${String(incident.severity || '').toLowerCase()}`}><ShieldAlert size={18} /></span><div><strong>{titleCase(incident.severity)} severity signal</strong><span>{relativeTime(incident.timestamp)} · {incident.status}</span></div></div><div className="detail-grid"><Detail label="Incident ID" value={incident.id} /><Detail label="Bus ID" value={incident.bus_id} /><Detail label="Detection time" value={shortTime(incident.timestamp)} /><Detail label="Location" value={coord(incident.location)} /><Detail label="AI confidence" value={confidence(incident.confidence)} /><Detail label="Vehicle number" value={incident.vehicle_number || 'Not identified'} /></div>{incident.evidence_url && <a className="evidence-link" href={incident.evidence_url} target="_blank" rel="noreferrer"><ExternalLink size={15} /> Open evidence preview</a>}<div className="drawer-actions"><span>Update status</span><div>{incident.status !== 'ACKNOWLEDGED' && <button disabled={busy} onClick={() => changeStatus('ACKNOWLEDGED')}><Check size={15} /> Acknowledge</button>}{incident.status !== 'INVESTIGATING' && incident.status !== 'RESOLVED' && <button disabled={busy} onClick={() => changeStatus('INVESTIGATING')}><Search size={15} /> Investigate</button>}{incident.status !== 'RESOLVED' && <button className="resolve" disabled={busy} onClick={() => changeStatus('RESOLVED')}><Check size={15} /> Resolve</button>}</div></div></aside></div> }
function Detail({ label, value }) { return <div className="detail-item"><span>{label}</span><strong>{value}</strong></div> }
